export const LOGIN_INFO = "LOGIN_INFO"
export const CASE_DETAIL = "CASE_DETAIL"
export const APP_DETAIL = "APP_DETAIL"
export const GROUP_DETAIL = "GROUP_DETAIL"
export const SIDE_CHECK = "SIDE_CHECK"
export const SCENE_CHECK = "SCENE_CHECK"
export const LOGIN_FORWARD_PATH = "LOGIN_FORWARD_PATH"
export const OREKI_IP = "OREKI_IP"